//***********************************************
//All response code will be in 3 categories
//having 1st aplpabet char then 2 digit char
//E: Error, S: Success, I: Info
//e.g E100, S100, I100
//**********************************************

module.exports = {
  S100: 'verification code sent to your email',
  S101: 'Email should be between 5 and 50 char!',
  S102: 'Invalid email pattern!',
  S103: 'Password shoudl be string!',
  S104: 'Password should be between 5 and 50 char!',
  S105: 'Name should be string!',
  S106: 'Name should be between 5 and 50 char!',
  S107: 'Money account should be array!',
  S108: 'At least one MoneyAccount required!',
  S109: 'Income source should be array!',
  S110: 'At least one income source required!',
  S111: 'Expense source should be array!',
  S112: 'At least one expense source required!',
  S113: '',
  S114: '',
  S115: '',
  S116: '',
  S117: '',
  S118: '',
  S119: '',
  S120: '',
  S121: '',
  E100: 'Invalid Email!',
  E101: 'Invalid Password!',
  E102: 'Invalid Name!',
  E103: 'Invalid Money Account!',
  E104: 'Invalid IMoney Account Type!',
  E105: 'Invalid Money Account Name!',
  E106: 'Invalid Income Source!',
  E107: 'Invalid Income Source Name!',
  E108: 'Inavlid Expnese Source',
  E109: 'Invalid Expnese Source Name!',
  E110: 'Invalid Amount!',
  E111: 'Invalid Transaction Description!',
  E112: 'Token not found in request!',
  E113: 'Authorization Header not found!',
  E114: 'Token Expire!',
  E115: 'Invalid Token!',
  E116: 'Resource not matching with user',
  E117: 'We are having problem with connecting to DB..Dont worry, will be back soon',
  E118: 'Error Occured while sending email',
  E119: 'Invalid Email or password',
  E120: 'DB Error Occured while querying',
  E121: 'DB Error Occured while Saving',

  E122: 'Email not found on our system!',
  E123: 'Wrong password!',
  E124: 'User is already register and verified!',
  E125: 'Wrong Verification Code',
  E126: 'Invalid Signup Options!',
  E127: 'Please verify your email before signup!',
  E128: '!',
  E129: 'Invalid Income Source Name!',
  E130: 'Inavlid Expnese Source',
  E131: 'Invalid Expnese Source Name!',
  E131: 'Invalid Amount!',
  E132: 'Invalid Transaction Description!',
  E133: 'Token not found in request!',
  E134: 'Authorization Header not found!',
  E135: 'Token Expire!',
  E136: 'Invalid Token!',
  E137: 'Resource not matching with user',
  E138: 'We are having problem with connecting to DB..Dont worry, will be back soon',
  E139: 'Error Occured while sending email',
  E140: 'Invalid Email or password',
  E141: 'DB Error Occured while querying',
  E142: 'DB Error Occured while Saving'
}
