//***********************************************
//All response code will be in 3 categories
//having 1st aplpabet char then 2 digit char
//E: Error, S: Success, I: Info
//e.g E100, S100, I100
//**********************************************

module.exports = {
  S100: 'email sent..check your mail',
  S101: 'Group Member deleted Successfully',
  S102: 'Email Verified Successfully',
  S103: 'Transaction Saved Successfully',
  S104: 'Transaction Deleted Successfully',
  S105: 'Group Member Added Successfully!',
  S106: 'Notification has been sent to respective member !',
  S107: 'Notification deleted Successfully!',
  S108: 'Group Member Deleted Successfully!!',
  S109: 'Group Created!',
  S110: 'Group Deleted!',
  S111: '!',
  S112: '!',
  S113: '',
  S114: '',
  S115: '',
  S116: '',
  S117: '',
  S118: '',
  S119: '',
  S120: '',
  S121: '',
  E100: 'Invalid Email: should be max 50 char with valid pattern!',
  E101: 'Invalid Password: should be min 4 and max 30 char, AlphaNumeric with char(.*#@)!',
  E102: 'Invalid Name!',
  E103: 'Invalid Money Account!',
  E104: 'Invalid IMoney Account Type!',
  E105: 'Invalid Money Account Name!',
  E106: 'Invalid Income Source!',
  E107: 'Invalid Income Source Name!',
  E108: 'Inavlid Expnese Source',
  E109: 'Invalid Expnese Source Name!',
  E110: 'Invalid Amount!',
  E111: 'Invalid Transaction Description!',
  E112: 'Token not found in request!',
  E113: 'Authorization Header not found!',
  E114: 'Expired Token!',
  E115: 'Invalid Token!',
  E116: 'Illegal Token!',
  E117: 'connection to database has broken, we are looking into it',
  E118: 'Error Occured while sending email',
  E119: 'Invalid Email or password',
  E120: 'DB Error Occured while querying',
  E121: 'DB Error Occured while Saving',
  E122: 'This Email is not registerd with us!',
  E123: 'Wrong password!',
  E124: 'User is already register and verified!',
  E125: 'Wrong Verification Code',
  E126: 'Invalid Signup Options!',
  E127: 'Please verify your email before signup!',
  E128: 'Please generate the verif code first!',
  E129: 'User not found on our system!',
  E130: 'No individual trandaction data',
  E131: 'Invalid update: expense source!',
  E131: 'Invalid update: income source',
  E132: 'Invalid update: money account!',
  E133: 'Invalid update: password!',
  E134: 'Invalid udpate: email!',
  E135: 'Invalid update: phone!',
  E136: 'Invalid udpate: fullname!',
  E137: 'User not found ',
  E138: 'Account Updated successfully',
  E139: 'Invalid update Option!',
  E140: 'Invalid TrxId',
  E141: 'Invalid UserId',
  E142: 'No such group or email found ',
  E143: 'Invalid groupId',
  E144: 'You are not admin of this group, only admin can delete group/groupMember',
  E145: 'Invalid group update option',
  E146: 'Only Actual member can add himself to any group',
  E147: 'User alrady added in this group',
  E148: 'This GroupId not found on our system',
  E149: 'Group Name should be Minimum 4 char long',
  E150: 'This user is already a part of this group',
  E151: 'No such group created by you',
  E152: 'Group not found on our system',
  E153: 'Invalid Notification Id',
  E154: 'Invalid notification Type',
  E155: 'Invalid Group Members',
  E156: 'Admin can not delete himself from group',
  E157: 'Only Admin can delete group',
  E158: '',
  E159: '',
  E160: '',
  E161: '',
  E162: '',
  E163: '',
  E164: '',
  E165: '',
  E166: '',
  E167: '',
  E168: '',
  E169: '',
  E170: '',
  E171: ''
}
